spring:
  application:
    name: producer
  datasource:
    url: jdbc:postgresql://localhost:5432/quotewatch
    username: quotewatch_app
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: quotewatch-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

awesomeapi:
  base-url: https://economia.awesomeapi.com.br
  timeout-ms: 5000